- name: Install and configure Elasticsearch cluster
  hosts: all
  become: true
  vars:
    elasticsearch_config_file: /etc/elasticsearch/elasticsearch.yml
    kibana_config_file: /etc/kibana/kibana.yml
    ansible_user: devteam
    ansible_become_user: root
    ansible_become: yes
    ansible_become_method: su
  tasks:
    - name: Update the server and install yum-plugins-core package
      become: true
      yum:
        name: yum-utils
        state: present
        update_cache: yes

    - name: Update package cache and fix missing dependencies
      become: true
      yum:
        update_cache: yes
        name: java-11-openjdk-devel.x86_64
        state: present

    - name: Set JAVA_HOME Environment Variables
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-11"'
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/lib/jvm/java-11/bin"

    - name: Reload environment variables
      become: true
      shell: source /etc/environment

    - name: Verify JAVA_HOME environment variable
      command: echo $JAVA_HOME

    - name: Import Elasticsearch GPG key
      become: true
      become_method: sudo
      rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      become: true
      become_method: sudo
      yum_repository:
        name: elasticsearch
        description: Elasticsearch repository for 8.x packages
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      when: "'elasticsearch_nodes' in group_names"

    - name: Install ElasticSearch 8 on Rhell 8
      yum:
        name: elasticsearch
        state: present
      delegate_to: "{{ item }}"
      with_items: "{{ groups['elasticsearch_nodes'] }}"
      run_once: true

    - name: Generate Elasticsearch configuration file on all nodes
      template:
        src: elasticsearch.yml.j2
        dest: "{{ elasticsearch_config_file }}"
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'
      delegate_to: "{{ item }}"
      vars:
        node_roles: "{{ hostvars[item]['node_roles'] }}"
        node_name: "{{ hostvars[item]['node_name'] }}"
      loop: "{{ groups['elasticsearch_nodes'] }}"
        
    - name: Add Kibana repository
      become: true
      yum:
        name: https://artifacts.elastic.co/downloads/kibana/kibana-8.7.0-x86_64.rpm
        state: present
      when: "'kibana_nodes' in group_names"

    - name: Install Kibana on kibana01
      become: true
      yum:
        name: kibana
        state: present
      delegate_to: "{{ item }}"
      with_items: "{{ groups['kibana_nodes'] }}"
      run_once: true

    - name: Generate Kibana configuration file on kibana01
      template:
        src: kibana.yml.j2
        dest: "{{ kibana_config_file }}"
        owner: kibana
        group: kibana
        mode: '0644'
      delegate_to: "{{ item }}"
      with_items: "{{ groups['kibana_nodes'] }}"
      run_once: true

    - name: Enable Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes
      when: "'elasticsearch_nodes' in group_names"

    - name: Enable Kibana service
      systemd:
        name: kibana
        enabled: yes
      when: "'kibana_nodes' in group_names"
