- hosts: elasticsearch_nodes
  tasks:
    - name: Create a directory at ~/ named certs_old, skip if it exist on monintelk01
      file:
        path: ~/certs_old
        state: directory
      when: inventory_hostname == "monintelk01"

    - name: Move ~/elastic-stack-ca.p12 and ~/elastic-certificates.p12 to ~/certs_old on monintelk01 and rename the files with date parameter while moving.
      shell: |
        current_date=$(date +'%Y-%m-%d')
        if [ -f ~/elastic-stack-ca.p12 ]; then
          mv ~/elastic-stack-ca.p12 ~/certs_old/elastic-stack-ca-${current_date}.p12
        fi
        if [ -f ~/elastic-certificates.p12 ]; then
          mv ~/elastic-certificates.p12 ~/certs_old/elastic-certificates-${current_date}.p12
        fi
      when: inventory_hostname == "monintelk01"

    - name: Delete /etc/elasticsearch/elastic-certificates.p12 on monintelk01, monintelk02, monintelk01
      file:
        path: /etc/elasticsearch/elastic-certificates.p12
        state: absent

    - name: Create a self-signed certificate authority on monintelk01
      shell: /usr/share/elasticsearch/bin/elasticsearch-certutil ca --out ~/elastic-stack-ca.p12 --pass ""
      when: inventory_hostname == "monintelk01"

    - name: Create a certificate for the ElasticSearch node on monintelk01
      shell: /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca ~/elastic-stack-ca.p12 --ca-pass "" --out ~/elastic-certificates.p12 --pass ""
      when: inventory_hostname == "monintelk01"

    - name: Copy the certificate to ansible-node, /tmp
      fetch:
        src: ~/elastic-certificates.p12
        dest: /tmp/elastic-certificates.p12
        flat: yes
      when: inventory_hostname == "monintelk01"
    
    - name: Copy the certificate to monintelk01, monintelk02, monintelk01, /etc/elasticsearch from ansible-node
      copy:
        src: /tmp/elastic-certificates.p12
        dest: /etc/elasticsearch/elastic-certificates.p12
        owner: elasticsearch
        group: elasticsearch
        mode: 0644